Save computed dataset indexes in this folder;

Existing problem: REFER loader in python3 has a known bug, 
indexes generated by a separate loader written in python2.

Temporary solution: copy generated indexes generated by python2.
To be updated.
Or download cache from: https://drive.google.com/open?id=1i9fjhZ3cmn5YOxlacGMpcxWmrNnRNU4B
